// Builds the one-page PDF CV from the same content as the website.
//
//   npm run cv
//
// Writes cv/cv.tex, compiles it with Tectonic (brew install tectonic) and
// copies the result to public/, where the site links to it.
import { execFileSync } from "node:child_process";
import { copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { profile, links } from "../src/content/profile.js";
import { education, experience, headline, interests, languages, skills, summary } from "../src/content/about.js";
import { monthRange, yearRange } from "../src/lib/dates.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const cvDir = join(root, "cv");
const outDir = join(cvDir, ".out");
const pdfName = profile.cvUrl.replace(/^\//, "");

const special = { "\\": "\\textbackslash{}", "&": "\\&", "%": "\\%", $: "\\$", "#": "\\#", _: "\\_", "{": "\\{", "}": "\\}", "~": "\\textasciitilde{}", "^": "\\textasciicircum{}" };
const tex = (s) => String(s).replace(/[\\&%$#_{}~^]/g, (c) => special[c]);

const bullets = (items) =>
  items.length === 0
    ? ""
    : `\\begin{itemize}\n${items.map((b) => `  \\item ${tex(b)}`).join("\n")}\n\\end{itemize}`;

const entry = (e, dates) => `\\entry{${tex(e.title)}}{${tex(e.org)}}{${tex(dates)}}
${bullets(e.bullets)}
\\entryend`;

// Skill items are separate lines on the site but one comma-separated line
// here, so generic words drop their capital ("Tool use" -> "tool use") while
// names like React or Claude Code keep theirs.
const properNames = /^(React|Next\.js|Node\.js|Supabase|Vercel|Docker|Stripe|Claude|Cursor|Git|Python|FastAPI|Express|Tailwind)\b/;
const inList = (item, i) =>
  i === 0 || properNames.test(item) || /^.[A-Z0-9]/.test(item) ? item : item[0].toLowerCase() + item.slice(1);

const sideGroup = (label, items) => `\\sidelabel{${tex(label)}}
${items.map((item, i) => tex(inList(item, i))).join(", ")}
\\sidegap`;

const linkedin = links.find((l) => l.label === "LinkedIn");
const github = links.find((l) => l.label === "GitHub");

const source = `% Generated by scripts/build-cv.mjs from src/content. Don't edit by hand:
% change the content files (or the template in the script) and run \`npm run cv\`.
\\documentclass[10pt]{article}
\\usepackage[a4paper,top=15mm,bottom=13mm,left=17mm,right=17mm]{geometry}
\\usepackage{fontspec}
\\setmainfont{SchibstedGrotesk}[Path=fonts/, Extension=.ttf, UprightFont=*-Regular, BoldFont=*-Medium, ItalicFont=*-Italic]
\\usepackage{xcolor}
\\definecolor{ink}{HTML}{14181D}
\\definecolor{muted}{HTML}{58616C}
\\definecolor{line}{HTML}{D3D9DF}
\\definecolor{accent}{HTML}{1E3FC4}
\\definecolor{photo}{HTML}{CFD4D8}
\\usepackage{graphicx}
\\usepackage{tikz}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\hypersetup{pdftitle={${tex(profile.name)}, CV}, pdfauthor={${tex(profile.name)}}}

\\usepackage{ragged2e}
\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{0pt}
\\fontsize{9.5}{13}\\selectfont
\\color{ink}
\\RaggedRight
\\hyphenpenalty=10000
\\exhyphenpenalty=10000

\\setlist[itemize]{leftmargin=9pt, itemsep=1pt, parsep=0pt, topsep=3pt, label={\\color{muted}\\textbullet}}

\\newcommand{\\cvsection}[1]{{\\fontsize{12.5}{15}\\selectfont\\bfseries #1}\\par\\vspace{3pt}{\\color{line}\\rule{\\linewidth}{0.6pt}}\\par\\vspace{6pt}}
\\newcommand{\\entry}[3]{{\\fontsize{10.5}{13}\\selectfont\\bfseries #1}\\hfill{\\color{muted}#3}\\par{\\color{muted}#2}\\par}
\\newcommand{\\entryend}{\\par\\vspace{9pt}}
\\newcommand{\\sidelabel}[1]{{\\color{muted}#1}\\par\\vspace{2pt}}
\\newcommand{\\sidegap}{\\par\\vspace{7pt}}

\\begin{document}

% Header: name, title, summary and contact on the left; portrait in a grey frame on the right.
\\begin{minipage}[b]{0.72\\linewidth}
{\\fontsize{30}{32}\\selectfont\\bfseries ${tex(profile.name)}}\\par\\vspace{6pt}
{\\fontsize{14}{17}\\selectfont\\color{accent}${tex(headline)}}\\par\\vspace{12pt}
{\\fontsize{10.5}{14.5}\\selectfont ${tex(summary)}}\\par\\vspace{12pt}
\\href{mailto:${profile.email}}{${tex(profile.email)}}\\quad
\\href{tel:${profile.phone.replace(/\s/g, "")}}{${tex(profile.phone)}}\\quad
\\href{https://${profile.website}}{${tex(profile.website)}}\\par\\vspace{2pt}
\\href{${github.href}}{${tex(github.href.replace("https://", ""))}}\\quad
\\href{${linkedin.href}}{LinkedIn}\\quad
{\\color{muted}${tex(profile.location)}}
\\end{minipage}\\hfill
\\begin{minipage}[b]{0.21\\linewidth}
\\begin{tikzpicture}
  \\fill[photo] (0,0) rectangle (\\linewidth, 1.396*\\linewidth);
  \\node[anchor=south west, inner sep=0] at (0,0) {\\includegraphics[width=\\linewidth]{portrait.png}};
\\end{tikzpicture}
\\end{minipage}

\\vspace{14pt}

% Body: experience on the left, everything else on the right.
\\begin{minipage}[t]{0.62\\linewidth}
\\cvsection{Experience}
${experience.map((e) => entry(e, monthRange(e))).join("\n")}
\\vspace{4pt}
\\begin{minipage}[t]{0.47\\linewidth}
\\cvsection{Languages}
${languages.map((l) => `${tex(l.name)}, ${tex(l.level)}\\par`).join("\n")}
\\end{minipage}\\hfill
\\begin{minipage}[t]{0.47\\linewidth}
\\cvsection{Outside work}
${interests.map((i) => `${tex(i)}\\par`).join("\n")}
\\end{minipage}

\\vspace{14pt}
{\\color{muted}Case studies and more at} \\href{https://${profile.website}}{${tex(profile.website)}}
\\end{minipage}\\hfill
\\begin{minipage}[t]{0.32\\linewidth}
\\cvsection{Education}
${education.map((e) => `{\\bfseries ${tex(e.title)}}\\par
{\\color{muted}${tex(e.org)}, ${tex(yearRange(e))}}\\par
${e.bullets.map((b) => `\\vspace{2pt}${tex(b)}\\par\n`).join("")}\\vspace{8pt}`).join("\n")}
\\vspace{4pt}
\\cvsection{Skills}
${skills.map((g) => sideGroup(g.group, g.items)).join("\n")}
\\end{minipage}

\\end{document}
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(cvDir, "cv.tex"), source);
// ~40 mm wide in print, so 520 px is still well over 300 dpi.
await sharp(join(root, "src/assets/img/portrait.webp")).resize({ width: 520 }).png({ palette: true, quality: 90 }).toFile(join(cvDir, "portrait.png"));

execFileSync("tectonic", ["--chatter", "minimal", "--outdir", ".out", "cv.tex"], { cwd: cvDir, stdio: "inherit" });
copyFileSync(join(outDir, "cv.pdf"), join(root, "public", pdfName));
console.log(`CV written to public/${pdfName}`);
